version: 2
updates:
  # Fichier package.json du Backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Fichier package.json du Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Surveillance des versions des GitHub Actions elles-mêmes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"